name: dart_movies_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  animated_text_kit: ^4.2.2
  http: ^1.2.1
  flutter_bloc: ^8.1.5
  hive: ^2.2.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Poppins-Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: Poppins-ExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
    
